apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 10m
  chart:
    spec:
      chart: vaultwarden
      version: "1.2.1"
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
  values:
    domain: "https://vault.sovereign.local"
    signupsAllowed: false
    persistence:
      enabled: true
      size: 5Gi
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: vault.sovereign.local
          paths:
            - path: /
              pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
